version: 0.0
os: linux
files:
  - source: /
    destination: /opt/prod
hooks:
  ApplicationStart:
    - location: ./start_prod_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop_server.sh
      timeout: 300
      runas: root